files: ^setup.py|^guild/|^examples/
exclude: ^guild/tests/

default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--diff']
        verbose: true

  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args: ['--errors-only']
        verbose: true
        exclude: ^examples/
        additional_dependencies:
          - Pillow>=5.0
          - chardet
          - click
          - daemonize
          - filelock
          - jinja2<3.1
          - natsort
          - pip
          - pkginfo
          - psutil
          - pydantic
          - pytest
          - pyyaml
          - scikit-learn
          - scikit-optimize
          - setuptools
          - sybil
          - tabview
          - tensorboard
          - twine

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^guild/op_main.py
      - id: end-of-file-fixer
      - id: trailing-whitespace
