name: Build

on:
  # push:
  #   branches:
  #     - main

  # pull_request:
  #   branches:
  #     - main

  workflow_dispatch:
    inputs:
      run_with_ssh:
        type: boolean
        description: Run with SSH
        required: false
        default: false
      uat:
        type: boolean
        description: Run full test suite (user acceptance)
        required: false
        default: false

jobs:
  build-posix:
    name: Build - POSIX
    runs-on: ${{ matrix.os }}
    # TODO: disabled for Windows dev
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        # ssh action (below) waits for a 'continue' sentinel - we want
        # the job to continue while ssh is available for connections
        run: touch continue

      - name: Start SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        uses: mxschmitt/action-tmate@v3

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python setup.py bdist_wheel

      - name: Install package
        run: |
          python -m venv test-env
          test-env/bin/pip install --upgrade pip
          test-env/bin/pip install dist/*.whl

      - name: Install test requirements
        # uat tests install test requirements as a part of the test
        # suite - these must not be installed ahead of time
        if: ${{ !inputs.uat }}
        run: |
          test-env/bin/pip install -r guild/tests/requirements.txt

      - name: Configure environment for tests
        # git config required by Guild tests that run git commands
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main

      - name: Run built-in tests
        if: ${{ !inputs.uat }}
        env:
          GUILD_START_THRESHOLD: 1.0
        run: |
          test-env/bin/guild check -nT

      - name: Run user acceptance tests
        if: ${{ inputs.uat }}
        env:
          EXAMPLES: examples
          GUILD_START_THRESHOLD: 1.0
          UAT_SKIP: remote-*,hiplot-*
          WORKSPACE: /tmp/guild-uat
        run: |
          test-env/bin/guild check --force-uat

      - name: Keep server alive for SSH (cancel job to terminate)
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        run: sleep 3600

  build-windows:
    name: Build - Windows
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          # - '3.6'
          # - '3.7'
          - '3.8'
          # - '3.9'
          # - '3.10'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        # ssh action (below) waits for a 'continue' sentinel - we want
        # the job to continue while ssh is available for connections
        run: touch continue

      - name: Start SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        uses: mxschmitt/action-tmate@v3

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python setup.py bdist_wheel

      - name: Install package
        run: |
          python -m venv test-env
          test-env\scripts\python -m pip install --upgrade pip
          pwsh -Command 'test-env\scripts\pip install $(ls dist)'

      - name: Install test requirements
        # uat tests install test requirements as a part of the test
        # suite - these must not be installed ahead of time
        if: ${{ !inputs.uat }}
        run: |
          test-env\scripts\pip install -r guild\tests\requirements.txt

      - name: Configure environment for tests
        # git config required by Guild tests that run git commands
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main

      - name: Run built-in tests
        if: ${{ !inputs.uat }}
        env:
          GUILD_START_THRESHOLD: 1.0
        run: |
          test-env\scripts\guild check -nT

      - name: Run user acceptance tests
        if: ${{ inputs.uat }}
        env:
          EXAMPLES: examples
          GUILD_START_THRESHOLD: 1.0
          UAT_SKIP: remote-*,hiplot-*
          WORKSPACE: /tmp/guild-uat
        run: |
          test-env\scripts\guild check --force-uat

      - name: Keep server alive for SSH (cancel job to terminate)
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        run: Start-Sleep 3600
