name: Debug

on:
  workflow_dispatch:
    inputs:
      os:
        description: OS to debug
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      python:
        description: Python version to debug
        options:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

jobs:
  debug:
    name: Debug ${{ inputs.os }} python-${{ inputs.python }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python }}

      - name: Start SSH
        if: ${{ (success() || failure()) }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        run: touch continue

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python setup.py bdist_wheel

      - name: Install package
        run: |
          python -m venv test-env
          test-env/bin/pip install --upgrade pip
          test-env/bin/pip install dist/*.whl

      - name: Configure environment for tests
        # git config required by Guild tests that run git commands
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main

      - name: Keep server alive for SSH (cancel workflow to terminate)
        if: ${{ (success() || failure()) }}
        run: sleep 7200
