name: Debug

on:
  workflow_dispatch:
    inputs:
      os:
        description: OS to debug
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      python:
        description: Python version to debug
        type: choice
        options:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
      run_tests:
        description: Run built-in tests
        type: boolean
        default: false
      run_uat:
        description: Run user acceptance tests
        type: boolean
        default: false

jobs:
  debug:
    name: Debug ${{ inputs.os }} python-${{ inputs.python }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python }}

      - name: Configure SSH
        # ssh action (below) waits for a 'continue' sentinel - we want
        # the job to continue while ssh is available for connections
        run: touch continue

      - name: Start SSH
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python setup.py bdist_wheel

      - name: Install package
        run: |
          python -m venv test-env
          test-env/bin/pip install --upgrade pip
          test-env/bin/pip install dist/*.whl

      - name: Configure environment for tests
        # git config required by Guild tests that run git commands
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main

      - name: Run built-in tests
        if: ${{ inputs.run_tests }}
        env:
          GUILD_START_THRESHOLD: 1.0
          BREAKPOINT_PROMPT_TIMEOUT: 5.0
          GUILD_CI: 1
          GH_TOKEN: ${{ github.token }}
        run: |
          test-env/bin/guild check -T -c8 --fast

      - name: Run user acceptance tests
        if: ${{ inputs.run_uat }}
        env:
          WORKSPACE: /tmp/guild-uat
          EXAMPLES: examples
          GUILD_CI: 1
          UAT_SKIP: remote-*,hiplot-*
          GUILD_START_THRESHOLD: 1.0
          DASK_SPEEDUP_THRESHOLD: 0
          BREAKPOINT_PROMPT_TIMEOUT: 5.0
          GH_TOKEN: ${{ github.token }}
        run: |
          test-env/bin/guild check --force-uat

      - name: Keep server alive for SSH (cancel workflow to terminate)
        run: sleep 7200
